spring:
  application:
    name: eSanarRestApi

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:enf123}
    password: ${DB_PASSWORD:sanar123}
    url: ${DB_URL:jdbc:postgresql://localhost:5433/enf_sanar}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  security:
    jwt:
      private:
        key: ${JWT_KEY:df077d8f28a73a9350111cf6832caf1d1a03353748f1ed02e2d1d91dae7ff121_}
    user:
      generator: ${JWT_USER:restSanarJWT}

